### ISSUE TITLE
Verification checksum is invalid for offloading with Cray clang 11 targeting AMD GFX908

### ISSUE THREAD

**Issue by mtbc** [ANL-CESAR/XSBench#18]
I am using XSBench to give toolchains on [Spock](https://docs.olcf.ornl.gov/systems/spock_quick_start_guide.html) a try. Building openmp-offload with Cray clang version 12.0.1 and MPICH 8.1.4, with PE_MPICH_GTL_LIBS_amd_gfx908="-lmpi_gtl_hsa", XSBench seems to run fine except for,

```
================================================================================
                                  INPUT SUMMARY
================================================================================
Programming Model:            OpenMP Target Offloading
Simulation Method:            Event Based
Grid Type:                    Unionized Grid
Materials:                    12
H-M Benchmark Size:           large
Total Nuclides:               355
Gridpoints (per Nuclide):     11,303
Unionized Energy Gridpoints:  4,012,565
Total XS Lookups:             17,000,000
MPI Ranks:                    1
Mem Usage per MPI Rank (MB):  5,649
Binary File Mode:             Off

...

================================================================================
                                     RESULTS
================================================================================
MPI ranks:   1
Total Lookups/s:            8,895,331
Avg Lookups/s per MPI rank: 8,895,331
Verification checksum: 904279 (WARNING - INAVALID CHECKSUM!)
```
The executable was linked by,
```
cc -std=gnu99 -Wall -I/sw/spock/spack-envs/views/rocm-4.1.0/include -fopenmp -D__STRICT_ANSI__  -g -pg -O3 -DMPI Main.o io.o Simulation.o GridInit.o XSutils.o Materials.o -o XSBench -lm -L/sw/spock/spack-envs/views/rocm-4.1.0/lib -lamdhip64 -lhsa-runtime64 -g -pg
```
As well as the expected output, it also prints a,
```
srun: error: spock31: task 0: Exited with exit code 1
```
(with the "31" varying) but I guess this simply reflects the checksum invalidity.

On a different Cray AMD GFX908 system, the offload version of XSBench works fine with ROCm. 

On the system with the failing checksum, https://github.com/jtramm/omp_target_issues/tree/master/simple built with,
```
cc -fopenmp -I/sw/spock/spack-envs/views/rocm-4.1.0/include -L/sw/spock/spack-envs/views/rocm-4.1.0/lib -lamdhip64 -lhsa-runtime64 main.cpp -o test
```
repeats a few, "Hello world from accelerator."

Is there anything I can provide to help you diagnose the issue? Would it be better for me to reach out to the Spock admins?

**Comment by jtramm** [comment]
The checksum XSBench generates is expected to be consistent across all architectures/compilers, as it is not making use of any intrinsic functions or anything that might cause changes in results. For instance, XSBench includes its own random number generator so that the same random stream is always produced. If the checksum is coming up as invalid that means there is (probably) a compiler or OpenMP runtime bug of some sort. I recommend reaching out to the Cray compiler team. It could be an issue with the OpenMP reduction of the checksum itself, or could be something deeper.

Another test might be to see if the smaller problem size works, e.g.,:

`./XSBench -m event -s small`

**Comment by mtbc** [comment]
Thank you, good to know! In the end I'm afraid that I may have mixed up terminals or something in my report as I can reproduce the problem with Cray clang v11.0.4 but not any v12.0.* so this very much look like a bug on their side that is now fixed.
