### ISSUE TITLE
Unchecked malloc in GridInit causes segfaults

### ISSUE THREAD

**Issue by stephand** [ANL-CESAR/XSBench#2]
There are multiple unchecked mallocs in generate_energy_grid that can return NULL and then cause segfault when initialising the grid.  The one I stumbled upon was the one on line 98:

int * full = (int *) malloc( n_isotopes ...);

Could you please check the return values of the mallocs and bail?
Thanks!

**Comment by jtramm** [comment]
Thanks for pointing this out!

The malloc return value was originally not checked as it's not actually guaranteed to return NULL if the system is out of memory. This is dependent on the particular OS and how it handles memory allocation requests. OSX Darwin, for instance, will usually not return a NULL malloc, even for ridiculous sized allocations. To combat this issue, you'll notice that the code actually prints out the estimated memory usage requirements at the beginning of execution, so if an OOM seg fault occurs it should give the user a heads up as to what the issue might be.

I've added the check in though as it sounds like it would be useful for you.

Thanks again for bringing this up!
