### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by mquinson** [ANL-CESAR/XSBench#5]
Hello,

I am one of the maintainer of the SMPI simulator, a tool allowing to run real MPI application on top of simulated infrastructure. More info [here](http://people.irisa.fr/Martin.Quinson/blog/2018/0626/SimGrid-Full.pdf), in particular on slides 45 and 46.

We run nightly tests against most of the applications listed as a ProxyApp by the [Exascale Project](https://proxyapps.exascaleproject.org/), and as you certainly know, XSBench is one of them. For more info, head to our [compilation farm](https://github.com/simgrid/SMPI-proxy-apps/).

Since approximately 2 days, your code fails to compile with the following error:
```
smpicc -std=gnu99 -Wall -fopenmp -flto -O3 -DMPI -c CalculateXS.c -o CalculateXS.o
/home/ci/workspace/SMPI-proxy-apps/build_mode/SMPI/label/proxy-apps/Benchmarks/ECP/XSBench/src/Main.c: In function ‘main’:
/home/ci/workspace/SMPI-proxy-apps/build_mode/SMPI/label/proxy-apps/Benchmarks/ECP/XSBench/src/Main.c:40:6: error: ‘thread’ undeclared (first use in this function)
  if( thread == 0 )
      ^~~~~~
/home/ci/workspace/SMPI-proxy-apps/build_mode/SMPI/label/proxy-apps/Benchmarks/ECP/XSBench/src/Main.c:40:6: note: each undeclared identifier is reported only once for each function it appears in
/home/ci/workspace/SMPI-proxy-apps/build_mode/SMPI/label/proxy-apps/Benchmarks/ECP/XSBench/src/Main.c:71:8: warning: unused variable ‘index_data’ [-Wunused-variable]
  int * index_data = NULL;
        ^~~~~~~~~~
/home/ci/workspace/SMPI-proxy-apps/build_mode/SMPI/label/proxy-apps/Benchmarks/ECP/XSBench/src/Main.c:19:13: warning: unused variable ‘stat’ [-Wunused-variable]
  MPI_Status stat;
             ^~~~
Makefile:129: recipe for target 'Main.o' failed
```

I suspect that this is related to the changes that you introduced recently, isn't it?

Thanks a lot for maintaining this proxy app, that's really precious for the tool makers.
Martin.

**Comment by mquinson** [comment]
Sorry, my mistake, the bug seem to be related to [our patch](https://github.com/simgrid/SMPI-proxy-apps/tree/master/src/ECP/XSBench), that still applies to the recent version, but does not compile anymore. Sorry.

**Comment by jtramm** [comment]
Hey Martin,

Glad you were able to get this one fixed. Let me know if you run into any more issues with the new version!

-John

**Comment by mquinson** [comment]
Hello John,

I'm taking over the project because the engineer that was in charge of
it left last week. This may explain why I misread the error message,
sorry for the noise.

The new version works like a charm for us, thanks a lot.

You may still be interested in the SMPI project, maybe. I believe that
this is a wonderful tool when it comes to the software QA of MPI
applications. And it's open source!

Have a good one,
Mt.
