### ISSUE TITLE
code returns 1 even after success

### ISSUE THREAD

**Issue by adegomme** [ANL-CESAR/XSBench#7]
Hello,
It looks like since a23df67 only the first process will validate its results and return 0 in the end in case of success, all of the others will return 1, which could be misinterpreted by some wrappers.

**Comment by jtramm** [comment]
Thanks for pointing this out! I just pushed commit 1de157e to resolve this issue by having all MPI ranks check the verification code rather than just rank 0. Should behave as expected now, with all ranks returning success or failure codes as expected.

**Comment by adegomme** [comment]
Indeed it works. Thanks !
https://ci.inria.fr/simgrid/job/SMPI-proxy-apps/build_mode=SMPI,label=proxy-apps/lastCompletedBuild/testReport/(root)/projectroot/
